export const STORAGE_KEYS = {
  blockedSites: "blockedSites",
  cachedBlockedSites: "cachedBlockedSites",
  tempAllowMinutes: "tempAllowMinutes",
  increasingAllowDelayEnabled: "increasingAllowDelayEnabled",
  accessGateActionId: "accessGateActionId",
  showChatGptPeek: "showChatGptPeek",
  blockPageAlternatives: "blockPageAlternatives",
  llmProvider: "llmProvider",
  llmReviewStrictness: "llmReviewStrictness",
  llmLeisureAllowance: "llmLeisureAllowance",
  openAiModel: "openAiModel",
  openAiApiKey: "openAiApiKey",
  accessEffectIds: "accessEffectIds",
  grayscaleOnTemporaryAllow: "grayscaleOnTemporaryAllow",
  temporarilyAllowedGrayscaleHosts: "temporarilyAllowedGrayscaleHosts",
  temporarilyAllowedUrls: "temporarilyAllowedUrls",
  temporaryAllowUsageSession: "temporaryAllowUsageSession",
  pendingTemporaryAllowDelay: "pendingTemporaryAllowDelay",
  lastPeekPrompt: "lastPeekPrompt",
  lastPeekSite: "lastPeekSite",
  lastPeekUrl: "lastPeekUrl",
  localDailyStats: "localDailyStats",
  aiStudyQuizChallenges: "aiStudyQuizChallenges",
  githubContributionUsername: "githubContributionUsername",
  githubContributionRecentWindowMinutes: "githubContributionRecentWindowMinutes",
  builtGatePrompt: "builtGatePrompt",
  builtGateSpec: "builtGateSpec",
} as const;

export const ALARM_NAMES = {
  badgeRefresh: "refresh-temp-allow-badge",
  accessEffectsRefresh: "refresh-access-effects",
} as const;
